name = "Smesh"
uuid = "e2b06280-edec-413c-a3a2-1b4e389db7bf"
authors = ["Simone Chiocchetti <simone.chiocchetti@uni-koeln.de>", "Benjamin Bolm <benjamin.bolm@uni-koeln.de>", "Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.1.1"

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
smesh_jll = "e8c45408-479c-54df-ae5b-4501057d3a5a"

[compat]
Preferences = "1"
julia = "1.8"
