name: Documentation

on:
  push:
    branches:
      - 'main'
    tags: '*'
    paths-ignore:
      - '.github/workflows/ci.yml'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/ci.yml'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # BEGIN - Build smesh locally - remove once JLL package is available
      - name: Get smesh
        uses: actions/checkout@v4
        with:
          repository: trixi-framework/smesh
          path: smesh
      - name: Build smesh (Linux)
        run: |
          mkdir smesh/build && cd smesh/build
          cmake .. -DCMAKE_INSTALL_PREFIX=../install
          cmake --build .
          cmake --install .
          cd ../../docs
          cat << EOF > LocalPreferences.toml
          [Smesh]
          libsmesh = "$(pwd)/smesh/install/lib/libsmesh.so"
          EOF
      # END - Build smesh locally - remove once JLL package is available
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          show-versioninfo: true
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs --color=yes docs/make.jl
